### ISSUE TITLE
VSCode Extension

### ISSUE THREAD

**Issue by manvankaliber** [UltraCakeBakery/cssified-html#18]
###### Ideas
- Autocompletion for attribute names
... thats it lol

**Comment by UltraCakeBakery** [comment]
@justingolden21 any chance we could make a vscode extension together for `rgb studios` so I can use that foundation for this project?

**Comment by justingolden21** [comment]
So a simple rgbstudios vs code extension that you can branch off of for this? I'm down, will continue conversation in Discord
